name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - name: Deploy projects
      env:
        AWS_ACCESS_KEY_ID: '${{ secrets.AWS_KEY }}'
        AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_KEY }}'
      run: sh deploy.sh
