# dummy for changes without python updates
name: Pylint

on:
  push:
    paths-ignore:
      - '**.py'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: 'echo "No build required"'